export default {
    MOVIES: "MOVIES",
    CURRENT_PAGE: "CURRENT_PAGE" ,
    TOGGLE_LOADER: "TOGGLE_LOADER",
    REMOVE_FAVORITE_MOVIE: "REMOVE_FAVORITE_MOVIE",
    TOGGLE_SEARCH: "TOGGLE_SEARCH",
    TOGGLE_FAVORITES: "TOGGLE_FAVORITES",
    SHOW_TOAST_NOTIFY: "SHOW_TOAST_NOTIFY",
    ADD_FAVORITE_MOVIE: "ADD_FAVORITE_MOVIE",
    SAVE_FAVORITE_MOVIES: "SAVE_FAVORITE_MOVIES",
    LOAD_FAVORITE_MOVIES: "LOAD_FAVORITE_MOVIES",
    SETUP_MOVIE_IDS: "SETUP_MOVIE_IDS",
};